#!/usr/bin/env bash

set -e

# This script symlinks dotfiles into $HOME folder.
# Set LOCAL_DOTFILES env variable to access local/private dotfiles on an
# external folder
#
#     export LOCAL_DOTFILES="/Dropbox/local_dotfiles"
#

source ./helper.sh

echo ''
install_dotfiles
echo ''
install_dotfiles_local
